-- Deploy kanbanlike:01-base-tables to pg

BEGIN;

DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "list" CASCADE;
DROP TABLE IF EXISTS "card" CASCADE;
DROP TABLE IF EXISTS "label" CASCADE;
DROP TABLE IF EXISTS "card_has_label" CASCADE;

CREATE TABLE IF NOT EXISTS "user" (
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"first_name" TEXT NOT NULL,
"last_name" TEXT NOT NULL,
"email" TEXT NOT NULL,
"password" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "list" (
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"name" TEXT NOT NULL,
"position" INT NOT NULL,
"user_id" INT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "card" (
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"name" TEXT NOT NULL,
"position" INT NOT NULL,
"status" TEXT NOT NULL DEFAULT 'in progress',
"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
"updated_at" TIMESTAMPTZ,
"list_id" INT NOT NULL REFERENCES "list"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "label" (
"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"name" TEXT NOT NULL,
"color" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "card_has_label" (
"card_id" INT NOT NULL REFERENCES "card"("id") ON DELETE CASCADE,
"label_id" INT NOT NULL REFERENCES "label"("id") ON DELETE CASCADE
);

COMMIT;

